extraVars:
  application: GenNext2-Documents

  backup_source_paths: E:\Websites\GenNext\GN2DocumentsDEV
  backup_destination_path: E:\GenNext\Backup\GenNext2DocumentsDev
  temp_extract_path: E:\CICD

  copy_jobs:
    - source_path: null
      destination_path: E:\Websites\GenNext\GN2DocumentsDEV
      exclude_paths:
        - AHASposeDocumentTemplates\AU\Endorsements
        - AHASposeDocumentTemplates\HK\Endorsements
        - AHASposeDocumentTemplates\MY\Endorsements
        - AHASposeDocumentTemplates\NZ\Endorsements
        - AHASposeDocumentTemplates\PH\Endorsements
        - AHASposeDocumentTemplates\SG\Endorsements
        - AHASposeDocumentTemplates\TW\Endorsements

  config_env: test